// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sample/ent/petattribute"
	"sample/ent/predicate"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// PetAttributeDelete is the builder for deleting a PetAttribute entity.
type PetAttributeDelete struct {
	config
	hooks    []Hook
	mutation *PetAttributeMutation
}

// Where adds a new predicate to the PetAttributeDelete builder.
func (pad *PetAttributeDelete) Where(ps ...predicate.PetAttribute) *PetAttributeDelete {
	pad.mutation.predicates = append(pad.mutation.predicates, ps...)
	return pad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pad *PetAttributeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pad.hooks) == 0 {
		affected, err = pad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PetAttributeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pad.mutation = mutation
			affected, err = pad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pad.hooks) - 1; i >= 0; i-- {
			mut = pad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pad *PetAttributeDelete) ExecX(ctx context.Context) int {
	n, err := pad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pad *PetAttributeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: petattribute.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: petattribute.FieldID,
			},
		},
	}
	if ps := pad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pad.driver, _spec)
}

// PetAttributeDeleteOne is the builder for deleting a single PetAttribute entity.
type PetAttributeDeleteOne struct {
	pad *PetAttributeDelete
}

// Exec executes the deletion query.
func (pado *PetAttributeDeleteOne) Exec(ctx context.Context) error {
	n, err := pado.pad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{petattribute.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pado *PetAttributeDeleteOne) ExecX(ctx context.Context) {
	pado.pad.ExecX(ctx)
}
